# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-11 22:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('midsemDateTime', models.DateTimeField()),
                ('compreDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomNumber', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionNumber', models.IntegerField()),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='project_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practical'), ('I', 'Independent')], max_length=20)),
                ('days', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('instructor1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subSection1', to='project_app.Instructor')),
                ('instructor2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subSection2', to='project_app.Instructor')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subSection', to='project_app.Room')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subSection', to='project_app.Section')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseIC',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='InstructorIncharge', to='project_app.Instructor'),
        ),
    ]
