# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-10 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20191111_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='ltp',
        ),
    ]
